name: flash_chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^3.1.0
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_spinkit: ^4.1.2+1
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
